#!/usr/bin/env bash
# Generate the release keystore once, outside the repo, and write the gitignored
# keystore.properties that the Gradle build reads.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
keystore_dir="${COUNTDOWN_KEYSTORE_DIR:-$HOME/.android-keystores}"
keystore="$keystore_dir/countdown-release.jks"
props="$repo_root/keystore.properties"
alias="countdown"

if [[ -f "$keystore" ]]; then
  echo "Keystore already exists at $keystore — leaving it alone."
else
  mkdir -p "$keystore_dir"
  chmod 700 "$keystore_dir"
  password="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
  keytool -genkeypair \
    -keystore "$keystore" \
    -storetype PKCS12 \
    -storepass "$password" \
    -alias "$alias" \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10950 \
    -dname "CN=Countdown, OU=Personal, O=notnot.ninja, C=ZA"
  chmod 600 "$keystore"
  echo "Generated $keystore"

  cat > "$props" <<EOF
# Generated by tools/make-keystore.sh. Gitignored — do not commit.
storeFile=$keystore
storePassword=$password
keyAlias=$alias
keyPassword=$password
EOF
  chmod 600 "$props"
  echo "Wrote $props"
fi

if [[ ! -f "$props" ]]; then
  echo "Keystore exists but $props does not." >&2
  echo "Copy keystore.properties.example and fill in the passwords." >&2
  exit 1
fi
